//
//  SportsMenListViewController.swift
//  HastenSports
//
//  Created by Pablo Vélez  on 03/12/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SportsMenListViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: SportsMenListPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension SportsMenListViewController: SportsMenListViewInterface {
    func reloadData() {
        
    }
    
}
