//
//  SportsMenListInterfaces.swift
//  HastenSports
//
//  Created by Pablo Vélez  on 03/12/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum SportsMenListNavigationOption {
}

protocol SportsMenListWireframeInterface: WireframeInterface {
    func navigate(to option: SportsMenListNavigationOption)
}

protocol SportsMenListViewInterface: ViewInterface {
}

protocol SportsMenListPresenterInterface: PresenterInterface {
}

protocol SportsMenListInteractorInterface: InteractorInterface {
}
