//
//  SportsMenListInterfaces.swift
//  HastenSports
//
//  Created by Pablo Vélez  on 03/12/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum SportsMenListNavigationOption {
}

protocol SportsMenListWireframeInterface: WireframeInterface {
    func navigate(to option: SportsMenListNavigationOption)
}

protocol SportsMenListViewInterface: ViewInterface {
    func reloadData()
}

protocol SportsMenListPresenterInterface: PresenterInterface {
    func startFechData()
    func numberOfSections() -> Int
    func section(at indexPath: IndexPath) -> PlayerListElement
    func numberOfItems() -> Int
    func item(at indexPath: IndexPath) -> Player
    func didSelectItem(at indexPath: IndexPath)
}

protocol SportsMenListInteractorInterface: InteractorInterface {
    @discardableResult
    func getSportsMenList(_ completion: @escaping SportsMenListCompletionBlock) -> DataRequest
}
