//
//  SportsMenListInteractor.swift
//  HastenSports
//
//  Created by Pablo Vélez  on 03/12/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SportsMenListInteractor {
}

// MARK: - Extensions -

extension SportsMenListInteractor: SportsMenListInteractorInterface {
}
