//
//  SportsMenListInteractor.swift
//  HastenSports
//
//  Created by Pablo Vélez  on 03/12/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Alamofire

final class SportsMenListInteractor {
    private let _sportsMenService = SportsMenListService()
}

// MARK: - Extensions -

extension SportsMenListInteractor: SportsMenListInteractorInterface {
    
    @discardableResult
    func getSportsMenList(_ completion: @escaping SportsMenListCompletionBlock) -> DataRequest {
        return _sportsMenService.getSportsMenList(completion)
    }
    
}
