//
//  SportsMenListPresenter.swift
//  HastenSports
//
//  Created by Pablo Vélez  on 03/12/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SportsMenListPresenter {

    // MARK: - Private properties -

    private unowned var _view: SportsMenListViewInterface
    private var _interactor: SportsMenListInteractorInterface
    private var _wireframe: SportsMenListWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: SportsMenListWireframeInterface, view: SportsMenListViewInterface, interactor: SportsMenListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension SportsMenListPresenter: SportsMenListPresenterInterface {
}
