//
//  SportsMenListWireframe.swift
//  HastenSports
//
//  Created by Pablo Vélez  on 03/12/2018.
//  Copyright (c) 2018 Denis. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SportsMenListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "SportsMenList", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: SportsMenListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = SportsMenListInteractor()
        let presenter = SportsMenListPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SportsMenListWireframe: SportsMenListWireframeInterface {

    func navigate(to option: SportsMenListNavigationOption) {
    }
}
